GET http://localhost:8080/api/status HTTP/1.1
###

GET http://localhost:8080/api/user/auth HTTP/1.1
content-type: application/json

{
    "name": "User test",
    "email": "testuser@gmail.com",
    "password": 123456
}

###
GET http://localhost:8080/api/user/testuser@gmail.com HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoVXNlciI6eyJpZCI6MSwibmFtZSI6IlVzZXIgdGVzdCIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIn0sImlhdCI6MTY3NDE4NjcxMiwiZXhwIjoxNjc0MjczMTEyfQ.3IOUIgWLSHUTCzL4EIM-2SMM8XOF4LowCwQOjmFRQPs

###
POST http://localhost:8080/api/user/register HTTP/1.1
content-type: application/json

{
    "name": "User test",
    "email": "testuser@gmail.com",
    "password": "123456"
}

###
PATCH  http://localhost:8080/api/user/ HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoVXNlciI6eyJpZCI6MSwibmFtZSI6IlVzZXIgdGVzdCIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIn0sImlhdCI6MTY3NDYyODI0NywiZXhwIjoxNjc0NzE0NjQ3fQ.X1808msli0pZ_6v6yDg2rXgiPHgElMAxsoU7DzV1tAw
